env:
  global:
    secure: Op+Uyva+4SODr2w0PsQCsO17ep4TsgqSgslMJLEu/muC1vfKdsKcPgXSjRqhRe0h+oK6ActSrEFCXm6SAEOOcLYH2EIQjgKu2O4jsrNC4LfclsK+DWS/HlgT55+eRtq2qnCgvFUWs9HvrMuMS+cPzTQP4bV7arrkVr7Td5Ry9ad33pHaQIPDv/y4zFritZ5wAcN6FYz1wf4gBGXL32e+FkxmQCmujhj+WqRHLNn0kYxLrzS9N76LZdnNhXq9oHBJQON4j+qVYGhliTwcYa3Hs3Y/dOv0cWrrDIelCqoUXlDjiz5km527hufRJOWRP2um7QFnY9w8mmSopfQUfnBTn5oLUXzNufNHBSvStk9J730W9tQa+aJCJrXi8avBZkI0V0QRA41DhAw0WSpTsOvZG0wvZBxcX/kQTwotqwMi96LCi8ymAysvAy05W13OsgQlq9T2SfJ7BbMcixtpAeL26DKhtI9qlZ2VZtBhNtjXKar5AOSbASWOVdDwK6Wz0hVgqUvsZUMKD8U0s084ZrfW41YGoOml+fD5+hxhY8qYr6kw+uAWNjNaHzRYgqYWelad8sq/oTJaoBiLKJeQwxgi+k7bfMsT4fXbcCl+xGPRv/6lqaXt1rbiZJ4Ma7DertbbPOnToU7RkS1JGN0HX/KqPHBjvk0b78oZmPDY8r/KHyM=

language: python # Set the build language to Python

#python: 3.6 # python version

branches: master # Set the branch to build from

install:
    - pip install mkdocs # Install the required dependencies
    - pip install mkdocs-material
    - pip install pymdown-extensions
    - git clone https://github.com/MrLeeh/markdown-lightbox.git
    - pip install markdown-lightbox/
    - mkdocs build
#    - pip install pygments
#    - git clean -f -d -x


