language: python
branches: master
services:
- docker
before_install:
- docker pull minlag/mermaid-cli:8.7.0
install:
- pip install markdown
- pip install pymdown-extensions
- pip install mkdocs
- pip install mkdocs-material
- pip install airscraper
- pip install rdflib
- pip install rdflib-jsonld
- pip install mkdocs-tooltipster-links-plugin
- pip install csvkit
- pip install requests
- pip install beautifulsoup4
- pip install mkdocs-macros-plugin
- pip install mkdocs-git-revision-date-localized-plugin
- pip install mkdocs-table-reader-plugin
- git clone https://github.com/g-provost/lightgallery-markdown.git
- cd lightgallery-markdown
- python setup.py install
- cd ..
script:
- git clean -f -d -x
- git clone https://github.com/chin-rcip/CRITERIA.git docs/et/CRITERIA
- git clone https://github.com/banditelol/airscraper.git docs/et/airscraper/airscraper
- cd docs/et/artworkCSV
- bash artwork.sh
- cd ../biblioCSV
- bash biblio.sh
- cd ../builtWorkCSV
- bash built_work.sh
- cd ../doCSV
- bash do.sh
- cd ../eventCSV
- bash event.sh
- cd ../groupCSV
- bash group.sh
- cd ../personCSV
- bash person.sh
- cd ../placeCSV
- bash place.sh
- cd ../../../
after_script:
- git config user.name "Nicola Carboni"
- git config user.email "nicola@carboni.me"
- git remote add gh-token "https://${GITHUB_TOKEN}@github.com/swiss-art-research-net/docs.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name gh-token;
env:
  global:
    secure: XRZ0UTMqk/h4h47dyPnaA3M0Vnaj+HaeVpwNpCxsaHTvYZOpjNp4JG3Qo5vQtbcx7ITPpPzyfP34YjUE6ZP89MIKCwM6C5VSxqw3N5voXShgtylNB7NBStxLLIpkWi2DT0E7aM5XZRgjTyFftFQKY2O6eXoaa9iunNaJr6ApLk6Mf3NpLUtTwDFkLomUNRgC2jTq6fwBqKPN/3AP97p5SVmXyQX+mGttGv1/R9gd5C7txestl6sFqtNNgAXjMHREiBRidHWlv8ajrGEV0s/FTPMmYndu3Udv/FAcY7A6ucuMT7VRL4D+uYdvY8Yu2y3cW4kq06XmkQAP8sw85P7LQ4SEKq2eodKcA6aZ77fNENAhtfq1/pkQCHHcsALnNCHubEprz0+m82+h1WO+EPkc/UFBnlbhRfIbBYD5sbQ5SfY26tCldZy0WXqTGTpIp9emEjeLCzLSl9QbOxSfMOFb00CvzRxwhZd9fd549PfQ2Q6QZiySKcjMpQyZH/GjrSljVBvYSCRCYHiKwNncGAeA1+2JRbdL5bTL2eLhos9vjb4DlVLcs8aUqp2XIOoX5xpXaznQZHX8yD234Vcuw40/uRko3OQ34XunnobVr5KX9/GL5ixRBQ/SqORSwAt+Go0IQGpZWLzgeov/FOT61XQoRTtlyYincBou980wQPpU5kE=
