site_name: SARI Documentation
#repo_url: https://github.com/swiss-art-research-net/docs
site_description: SARI Documentation

# Customization
extra:
  social:
    - type: globe
    - link: https://swissartresearch.net
  

# pagination  
nav:
    - Project Home: index.md
    - Entity Reference Model:
      - Instruction: instruction.md
      - Person : et/person.md
      - Artwork: et/artwork.md
      - Group: et/institution.md
      - Built Work: et/built_work.md
      - Event: et/event.md
      - Digital Object: et/do.md
    - Modelling Examples:
      - Instruction: pattern/instruction.md
      - Shared: pattern/general.md
      - Temporal: pattern/temporal.md
#     - Conceptual: pattern/conceptual.md
      - Physical: pattern/physical.md  
    - Ontology Extension:
      - Extension: schema.md

theme:
  name: 'material'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  font:
    text: 'Source Sans Pro'
    code: 'IBM Plex Mono'
  custom_dir: 'theme/'
  palette:
    primary: 'white'
 
markdown_extensions:
  - pymdownx.smartsymbols
#  - markdown
  - lightgallery
  - pymdownx.mark
  - markdown.extensions.attr_list
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - meta
  - footnotes
  - admonition
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format

  

extra_css:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
  - 'stylesheets/extra.css'
  - 'stylesheets/lightbox.css'
extra_javascript:
  - 'js/lightbox-plus-jquery.min.js'
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js