flowchart TD
classDef Literal fill:#ffffff,stroke:#000000,color:;
classDef Literal_URI fill:#ffffff,stroke:#000000,color:;
classDef crm_E1_CRM_Entity fill:#ffffff,stroke:#000000,color:;
classDef crm_E1_CRM_Entity_URI fill:#ffffff,stroke:#000000,color:;
classDef crm_E2_Temporal_Entity fill:#82ddff,stroke:#000000,color:;
classDef crm_E2_Temporal_Entity_URI fill:#d2effa,stroke:#000000,color:;
classDef crm_E55_Type fill:#fab565,stroke:#000000,color:;
classDef crm_E55_Type_URI fill:#fde7ce,stroke:#000000,color:;
classDef crm_E52_Time-Span fill:#86bcc8,stroke:#000000,color:;
classDef crm_E52_Time-Span_URI fill:#dcebef,stroke:#000000,color:;
classDef crm_E41_Appellation fill:#fef3ba,stroke:#000000,color:;
classDef crm_E41_Appellation_URI fill:#fffae6,stroke:#000000,color:;
classDef crm_E53_Place fill:#94cc7d,stroke:#000000,color:;
classDef crm_E53_Place_URI fill:#e1f1da,stroke:#000000,color:;
classDef crm_E77_Persistent_Item fill:#ffffff,stroke:#000000,color:;
classDef crm_E77_Persistent_Item_URI fill:#ffffff,stroke:#000000,color:;
classDef crm_E28_Conceptual_Object fill:#fddc34,stroke:#000000,color:;
classDef crm_E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000,color:;
classDef crm_E18_Physical_Thing fill:#c78e66,stroke:#000000,color:;
classDef crm_E18_Physical_Thing_URI fill:#e3c8b5,stroke:#000000,color:;
classDef crm_E39_Actor fill:#ffbdca,stroke:#000000,color:;
classDef crm_E39_Actor_URI fill:#ffe6eb,stroke:#000000,color:;
classDef crm_E54_Dimension fill:#b8b8b8,stroke:#000000,color:;
classDef crm_E54_Dimension_URI fill:#f2f2f2,stroke:#000000,color:;
classDef crm_E92_Spacetime_Volume fill:#cc80ff,stroke:#000000,color:;
classDef crm_E92_Spacetime_Volume_URI fill:#ebccff,stroke:#000000,color:;
classDef crm_E59_Primitive_Value fill:#f0f0f0,stroke:#000000,color:;
classDef crm_E59_Primitive_Value_URI fill:#f2f2f2,stroke:#000000,color:;
classDef crm_PC0_Typed_CRM_Property fill:#ffffff,stroke:#000000,color:;
classDef crm_PC0_Typed_CRM_Property_URI fill:#ffffff,stroke:#000000,color:;
classDef Multi fill:#cccccc,stroke:#000000,color:;
classDef Multi_URI fill:#cccccc,stroke:#000000,color:;
8["crm:E15_Identifier_Assignment"]:::crm_E2_Temporal_Entity -->|crm:P16_used_specific_object| 9["crm:E73_Information_Object"]:::crm_E28_Conceptual_Object
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P72_has_language| 10["crm:E56_Language"]:::crm_E55_Type
12["crm:E33_E41_Linguistic_Appellation"]:::Default -->|frbroo:R64i_was_name_used_by| 13["frbroo:F52_Name_Use_Activity"]:::Default
16["crm:E42_Identifier"]:::crm_E41_Appellation -->|crm:P190_has_symbolic_content| 17["xsd:string"]:::Literal
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 18["xsd:string"]:::Literal
12["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 6["crm:E55_Type"]:::crm_E55_Type
14["crm:E52_Time-Span"]:::crm_E52_Time-Span -->|crm:P82a_begin_of_the_begin| 22["xsd:dateTime"]:::Literal
26["crm:E17_Type_Assignment"]:::crm_E2_Temporal_Entity -->|crm:P4_has_time-span| 14["crm:E52_Time-Span"]:::crm_E52_Time-Span
24["crm:E53_Place"]:::crm_E53_Place -->|crm:P1_is_identified_by| 16["crm:E42_Identifier"]:::crm_E41_Appellation
24["crm:E53_Place"]:::crm_E53_Place -->|crm:P41i_was_classified_by| 26["crm:E17_Type_Assignment"]:::crm_E2_Temporal_Entity
29["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 30["crm:E55_Type"]:::crm_E55_Type
24["crm:E53_Place"]:::crm_E53_Place -->|crm:P2_has_type| 31["crm:E55_Type"]:::crm_E55_Type
26["crm:E17_Type_Assignment"]:::crm_E2_Temporal_Entity -->|crm:P42_assigned| 31["crm:E55_Type"]:::crm_E55_Type
14["crm:E52_Time-Span"]:::crm_E52_Time-Span -->|crm:P82b_end_of_the_end| 38["xsd:dateTime"]:::Literal
24["crm:E53_Place"]:::crm_E53_Place -->|crm:P1_is_identified_by| 12["crm:E33_E41_Linguistic_Appellation"]:::Default
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 27["crm:E55_Type"]:::crm_E55_Type
16["crm:E42_Identifier"]:::crm_E41_Appellation -->|crm:P37i_was_assigned_by| 8["crm:E15_Identifier_Assignment"]:::crm_E2_Temporal_Entity
12["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 41["xsd:string"]:::Literal
42["crm:E52_Time-Span"]:::crm_E52_Time-Span -->|crm:P82a_begin_of_the_begin| 43["xsd:dateTime"]:::Literal
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P106_is_composed_of| 29["crm:E33_E41_Linguistic_Appellation"]:::Default
0["crm:E13_Attribute_Assignment"]:::crm_E2_Temporal_Entity -->|crm:P16_used_specific_object| 34["crm:E73_Information_Object"]:::crm_E28_Conceptual_Object
42["crm:E52_Time-Span"]:::crm_E52_Time-Span -->|crm:P82b_end_of_the_end| 49["xsd:dateTime"]:::Literal
24["crm:E53_Place"]:::crm_E53_Place -->|crm:P1_is_identified_by| 2["crm:E33_E41_Linguistic_Appellation"]:::Default
13["frbroo:F52_Name_Use_Activity"]:::Default -->|crm:P4_has_time-span| 42["crm:E52_Time-Span"]:::crm_E52_Time-Span
8["crm:E15_Identifier_Assignment"]:::crm_E2_Temporal_Entity -->|crm:P14_carried_out_by| 32["crm:E39_Actor"]:::crm_E39_Actor
16["crm:E42_Identifier"]:::crm_E41_Appellation -->|crm:P2_has_type| 36["crm:E55_Type"]:::crm_E55_Type
12["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P141i_was_assigned_by| 0["crm:E13_Attribute_Assignment"]:::crm_E2_Temporal_Entity
12["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P72_has_language| 4["crm:E56_Language"]:::crm_E55_Type
0["crm:E13_Attribute_Assignment"]:::crm_E2_Temporal_Entity -->|crm:P14_carried_out_by| 19["crm:E39_Actor"]:::crm_E39_Actor
